version: '3.5'
services: 
  consul:
    container_name: consul100
    image: consul:1.2.1
    restart: always
    network_mode: "host"
    volumes:
      - /data/consul/config:/consul/config
      - /data/consul/data:/consul/data
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8500:8500
      - 8600:8600
      - 8765:8765